### ISSUE TITLE
cosmetics

### ISSUE THREAD

**Issue by 9000h** [flensrocker/vdr-plugin-dbus2vdr#21]
I have another warning when compiling the latest git
```
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -pthread -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -I/usr/include/libpng12 -c -DPLUGIN_NAME_I18N='"dbus2vdr"'  -o network.o network.c
network.c: In function ‘char* decode_event(GFileMonitorEvent)’:
network.c:27:10: warning: enumeration value ‘G_FILE_MONITOR_EVENT_RENAMED’ not handled in switch [-Wswitch]
   switch (ev) {
          ^
network.c:27:10: warning: enumeration value ‘G_FILE_MONITOR_EVENT_MOVED_IN’ not handled in switch [-Wswitch]
network.c:27:10: warning: enumeration value ‘G_FILE_MONITOR_EVENT_MOVED_OUT’ not handled in switch [-Wswitch]
```

**Comment by flensrocker** [comment]
These are new events not available on my platform. I use GLib 2.40 on Ubuntu Trusty, which version do you use?
I will switch to Ubuntu Xenial in the near future, don't know which version it has. I will take care of them as soon as the show up on my dev machine.

**Comment by 9000h** [comment]
it's Willy 15.10

**Comment by flensrocker** [comment]
Please try:

    diff --git a/network.c b/network.c
    index 37a7c35..5fd00b8 100644
    --- a/network.c
    +++ b/network.c
    @@ -33,5 +33,10 @@ static char *decode_event(GFileMonitorEvent ev)
         dc(PRE_UNMOUNT);
         dc(UNMOUNTED);
         dc(MOVED);
    +    default:
    +      strcat(fmt, "UNKNOWN");
    +      caret += strlen(#x);
    +      fmt[caret] = ':';
    +      break;
       }
     #undef dc

**Comment by 9000h** [comment]
compiles fine with the patch
